/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyReport {
  'day' : Time,
  'totalRevenue' : bigint,
  'transactionCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface InventoryItem {
  'id' : string,
  'purchasePrice' : bigint,
  'kind' : ItemKind,
  'name' : string,
  'sellingPrice' : bigint,
  'quantity' : [] | [bigint],
}
export type ItemKind = { 'service' : null } |
  { 'goods' : null };
export interface MonthlyReport {
  'month' : Time,
  'totalRevenue' : bigint,
  'transactionCount' : bigint,
}
export interface ShopSettings {
  'logo' : [] | [ExternalBlob],
  'address' : string,
  'shopName' : string,
  'phoneNumber' : string,
  'thankYouMessage' : string,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'customerName' : string,
  'vehicleInfo' : string,
  'total' : bigint,
  'timestamp' : Time,
  'items' : Array<TransactionItem>,
}
export interface TransactionItem {
  'id' : string,
  'name' : string,
  'itemType' : ItemKind,
  'quantity' : bigint,
  'price' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addCustomer' : ActorMethod<[string], undefined>,
  'addInventoryItem' : ActorMethod<
    [string, string, bigint, bigint, [] | [bigint], ItemKind],
    undefined
  >,
  'calculateProfitLoss' : ActorMethod<[Time, Time], bigint>,
  'createTransaction' : ActorMethod<
    [Array<TransactionItem>, bigint, string, string],
    bigint
  >,
  'deleteCustomer' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllCustomers' : ActorMethod<[], Array<string>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getDailyReport' : ActorMethod<[Time], DailyReport>,
  'getInventoryItem' : ActorMethod<[string], [] | [InventoryItem]>,
  'getMonthlyReport' : ActorMethod<[Time], MonthlyReport>,
  'getPersistentSettings' : ActorMethod<[], ShopSettings>,
  'getTopSellingItems' : ActorMethod<[bigint], Array<[string, bigint]>>,
  'getTransaction' : ActorMethod<[bigint], [] | [Transaction]>,
  'getTransactionsByCustomer' : ActorMethod<[string], Array<Transaction>>,
  'getTransactionsByMonth' : ActorMethod<[Time], Array<Transaction>>,
  'updateInventoryItemQuantity' : ActorMethod<[string, bigint], undefined>,
  'updatePersistentSettings' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'uploadLogo' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];