/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ItemKind = IDL.Variant({
  'service' : IDL.Null,
  'goods' : IDL.Null,
});
export const Time = IDL.Int;
export const TransactionItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'itemType' : ItemKind,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'kind' : ItemKind,
  'name' : IDL.Text,
  'sellingPrice' : IDL.Nat,
  'quantity' : IDL.Opt(IDL.Nat),
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'vehicleInfo' : IDL.Text,
  'total' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(TransactionItem),
});
export const DailyReport = IDL.Record({
  'day' : Time,
  'totalRevenue' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});
export const MonthlyReport = IDL.Record({
  'month' : Time,
  'totalRevenue' : IDL.Nat,
  'transactionCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ShopSettings = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'address' : IDL.Text,
  'shopName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'thankYouMessage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addCustomer' : IDL.Func([IDL.Text], [], []),
  'addInventoryItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), ItemKind],
      [],
      [],
    ),
  'calculateProfitLoss' : IDL.Func([Time, Time], [IDL.Nat], ['query']),
  'createTransaction' : IDL.Func(
      [IDL.Vec(TransactionItem), IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCustomer' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getDailyReport' : IDL.Func([Time], [DailyReport], ['query']),
  'getInventoryItem' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(InventoryItem)],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func([Time], [MonthlyReport], ['query']),
  'getPersistentSettings' : IDL.Func([], [ShopSettings], ['query']),
  'getTopSellingItems' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
  'getTransactionsByCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getTransactionsByMonth' : IDL.Func(
      [Time],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'updateInventoryItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updatePersistentSettings' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadLogo' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ItemKind = IDL.Variant({ 'service' : IDL.Null, 'goods' : IDL.Null });
  const Time = IDL.Int;
  const TransactionItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'itemType' : ItemKind,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'kind' : ItemKind,
    'name' : IDL.Text,
    'sellingPrice' : IDL.Nat,
    'quantity' : IDL.Opt(IDL.Nat),
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'vehicleInfo' : IDL.Text,
    'total' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(TransactionItem),
  });
  const DailyReport = IDL.Record({
    'day' : Time,
    'totalRevenue' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  const MonthlyReport = IDL.Record({
    'month' : Time,
    'totalRevenue' : IDL.Nat,
    'transactionCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ShopSettings = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'address' : IDL.Text,
    'shopName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'thankYouMessage' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addCustomer' : IDL.Func([IDL.Text], [], []),
    'addInventoryItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat), ItemKind],
        [],
        [],
      ),
    'calculateProfitLoss' : IDL.Func([Time, Time], [IDL.Nat], ['query']),
    'createTransaction' : IDL.Func(
        [IDL.Vec(TransactionItem), IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCustomer' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getDailyReport' : IDL.Func([Time], [DailyReport], ['query']),
    'getInventoryItem' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(InventoryItem)],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func([Time], [MonthlyReport], ['query']),
    'getPersistentSettings' : IDL.Func([], [ShopSettings], ['query']),
    'getTopSellingItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Nat], [IDL.Opt(Transaction)], ['query']),
    'getTransactionsByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getTransactionsByMonth' : IDL.Func(
        [Time],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'updateInventoryItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updatePersistentSettings' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadLogo' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };